version: '2.2'

services:
  mysql:
    image: mysql:8.3
    container_name: rasfood_mysql
    environment:
      MYSQL_DATABASE: rasfood
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: felipe
      MYSQL_PASSWORD: 123456
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local